ДЗ 3. Healthcheck Express server with Logger Stream
melkor101/nodejs_hw_ARTEM pull request #3
Opened 2024-12-14 21:01 UTC by melkor101

1) Зробити простий express healthcheck application на 2 endpoints: 

GET / - повертає "Hello world"

GET /healthcheck - повертає json:

{

  "live": true, 

  "timestamp": <current datetime in UTC>

}

2) допрацювати свій логгер що б він писав і у консоль і у файл 'server.log' у папці /logs

записи повинні робитися за допомогою Streams

3) зробити middleware http log який використовує Ваш логгер из пункта 2

2024-12-15 16:56 UTC, virtax requested changes

2024-12-15 16:56 UTC, virtax commented on homework2/main.js
> +
Краще не включати папки з інших домашек

2024-12-15 16:56 UTC, virtax commented on homework3/src/utils/logger.ts
> +    onLog(message: string) {
У логгері як і раніше потрібні два методи - log() та warn() (можна ще error() додати)

2024-12-15 16:56 UTC, virtax commented on homework3/src/utils/logger.ts
> +        writeStream.end();
У такому режимі стрім можна використовувати (якщо добавити { flags: 'a' }), но для цього більш зручні команди типу fs.appendFile(). Ідея була що б стрім відкрився на старті або при першому запису і закрився при остановці серверу (це робиться автоматично, бо є опція AutoClose яка true by default).
Тому пропоную переписати цю частину

2024-12-15 16:56 UTC, virtax commented on homework3/src/app.ts
> +const responseData = JSON.stringify({
Не треба json у строку переводити, треба використовувати   res.json()

2024-12-17 13:38 UTC, melkor101 commented on homework2/main.js
> +
PR-2 merged не актуально; В майбутньому буду мати на увазі, дякую

2024-12-17 13:39 UTC, melkor101 commented on homework3/src/utils/logger.ts
> +    onLog(message: string) {
виправив

2024-12-17 13:43 UTC, melkor101 commented on homework3/src/app.ts
> +const responseData = JSON.stringify({
виправив

2024-12-17 13:45 UTC, melkor101 commented on homework3/src/utils/logger.ts
> +        writeStream.end();
Змінив

2024-12-17 20:39 UTC, virtax requested changes

2024-12-17 20:39 UTC, virtax commented on homework3/src/utils/logger.ts
> +        writeStream.end();
writeStream.end(); не потрібен

2024-12-17 20:39 UTC, virtax commented on homework3/src/utils/logger.ts
> +        writeStream.end();
writeStream.end(); не потрібен

2024-12-18 05:46 UTC, melkor101 commented on homework3/src/utils/logger.ts
> +        writeStream.end();
removed

2024-12-18 05:46 UTC, melkor101 commented on homework3/src/utils/logger.ts
> +        writeStream.end();
removed

2024-12-18 15:36 UTC, virtax approved these changes
Ще було б гарно папку logs добавити у репозіторій, а так все добре

2024-12-18 15:36 UTC, merged